import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        
        <ul className="flex w-fill px-20 py-4 border m-10 gap-x-20">
          <li className="text-yellow-600 underline hover:no-underline"><Link href={'/about'}>About</Link></li>
          <li className="text-yellow-600 underline hover:no-underline"><Link href={'/login'}>Login</Link></li>
        </ul>
        
        {children}
        <h2>Footer Layout</h2>
        </body>
    </html>
  );
}
